# Generated by Django 4.1.5 on 2023-01-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, default='static/media/defaultBlogPic.png', null=True, upload_to='static/media/blog_images'),
        ),
    ]
