# Generated by Django 4.1.5 on 2023-01-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, default='defaultBlogPic.png', null=True, upload_to='blog_images'),
        ),
    ]
