# Generated by Django 4.1.5 on 2023-01-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='defaultAvatar.png', null=True, upload_to='profile_images'),
        ),
    ]
