# Generated by Django 4.1.5 on 2023-01-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='static/media/defaultAvatar.png', null=True, upload_to='static/media/profile_images'),
        ),
    ]
