# Generated by Django 4.1.5 on 2023-01-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='defaultAvatar.png', null=True, upload_to='profile_images'),
        ),
    ]
